import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Search, Stethoscope } from "lucide-react";
import Layout from "../components/Layout";
import api from "../services/api";
export default function Doctors(){
 const [doctors,setDoctors]=useState([]),[q,setQ]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);api.get("/doctors",{params:q?{search:q}:{}}).then(r=>{if(active)setDoctors(r.data)}).catch(e=>{if(active)setError(e.response?.data?.message||"Could not load doctors")}).finally(()=>active&&setLoading(false));return()=>{active=false}},[q]);
 return <Layout><div className="space-y-6"><div><div className="text-teal-300 text-sm">Care directory</div><h1 className="mt-1 text-4xl font-black">Find the right doctor.</h1><p className="mt-2 text-slate-400">Search by name or specialty.</p></div><div className="flex items-center rounded-xl border border-white/10 bg-white/5 px-4"><Search size={18} className="text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="e.g. cardiology, dermatology, Ananya" className="w-full bg-transparent px-3 py-3 outline-none"/></div>{error&&<div className="rounded-xl bg-red-400/10 p-4 text-red-200">{error}</div>}{loading?<div className="text-slate-400">Loading doctors…</div>:doctors.length===0?<div className="glass rounded-3xl p-8 text-slate-400">No doctors matched your search. Try “cardiology” or clear the search.</div>:<div className="grid gap-4 md:grid-cols-2">{doctors.map(({user,profile})=><div key={user._id} className="glass rounded-3xl p-6"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-400/10 text-violet-300"><Stethoscope/></div><span className="rounded-full bg-teal-300/10 px-3 py-1 text-xs text-teal-200">{profile?.specialization||"Specialist"}</span></div><h2 className="mt-5 text-xl font-bold">{user.name}</h2><p className="mt-1 text-sm text-slate-500">{profile?.qualification||"Medical professional"} · {profile?.experience||0} years experience</p><p className="mt-4 text-sm leading-6 text-slate-400">{profile?.bio||"Focused, patient-first consultations."}</p><Link to={`/patient/book/${user._id}`} className="mt-5 inline-block rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-950">View slots</Link></div>)}</div>}</div></Layout>
}
